defaults:
  - _self_
  - augmentations: custom_asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-l3d"
method: "byol"
backbone:
  name: "resnet50"
  use_pretrained: true
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
momentum:
  base_tau: 0.99
  final_tau: 1.0
  classifer: false
data:
  dataset: l3d
  train_path: "/home/xronis/mnt/L3D/data"
  val_path: null
  format: "none"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.45
  classifier_lr: 0.2
  weight_decay: 1e-6
  kwargs:
    clip_lr: False
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: None
precision: 16
accumulate_grad_batches: 16
#resume_from_checkpoint: /home/xronis/Projects/solo-learn/trained_models/byol-resnet50-imagenet-100ep-25x5nqle-ep=99.ckpt
