defaults:
  - _self_
  - augmentations: wmse.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "wmse-l3d"
method: "wmse"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 1024
  proj_output_dim: 64
  whitening_size: 128
data:
  dataset: l3d
  train_path: "/home/xronis/mnt/L3D/data"
  val_path: null
  format: "none"
  num_workers: 6
optimizer:
  name: "adam"
  batch_size: 128
  lr: 2e-3
  classifier_lr: 3e-3
  weight_decay: 1e-6
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: None
precision: 16
